#  Copyright (c) 2026. Jose Manuel Requena Plens
"""metrology domain of phonometry (see module docstrings).

Narrowed in 4.0 to the transverse metrology: calibration, GUM uncertainty,
data qualification, the ISO 1683 reference values every level is counted
from, the conformance rule the IEC TC 29 instrument standards written since
2013 grade an instrument by, the IEC 60942 verdict on the sound calibrator
every calibration starts from, the IEC 61183 random-incidence and
diffuse-field sensitivity of a sound level meter, the IEC 62585
corrections that bring a sound level meter on a calibrator, coupler or
actuator to its free-field response, the IEC 61672-3 verdict on the periodic
tests of a sound level meter, the calibration of a measurement microphone
by comparison with a reference microphone, in a pressure field by IEC 61094-5
and in a free field by IEC 61094-8, and the primary calibration of laboratory
standard microphones by reciprocity, in a coupler by IEC 61094-2 and in a free
field by IEC 61094-3. The filter banks and weightings moved to
:mod:`phonometry.filters`, the general signal analysis to
:mod:`phonometry.signals` and the IEC 61043 intensity-instrument class check
to :mod:`phonometry.emission.intensity_compliance`, which is what it verifies.
"""

from __future__ import annotations

from .calibration import CalibrationWarning, sensitivity
from .comparison_calibration import (
    IEC61094_5_TABLE_A1,
    IEC61094_5_TABLE_D1,
    IEC61094_8_TABLE_1,
    IEC61094_8_TABLE_2,
    ComparisonCalibration,
    ComparisonUncertaintyBudget,
    ComparisonUncertaintyRow,
    EnvironmentalSensitivityCorrection,
    FreeFieldRegion,
    JigDiameterCorrection,
    ReferenceCalibrationRow,
    comparison_uncertainty_budget,
    environmental_sensitivity_correction,
    free_field_region,
    jig_diameter_correction,
    sequential_comparison,
    simultaneous_comparison,
)
from .conformance import ConformanceVerification, verify_conformance
from .data_qualification import (
    LevelCrossingResult,
    PeakStatisticsResult,
    StationarityTestResult,
    TrendTestResult,
    level_crossing_rate,
    peak_statistics,
    stationarity_test,
    trend_test,
)
from .free_field_corrections import (
    IEC62585_TABLE_I1,
    AdjustmentValue,
    CorrectionUncertaintyBudget,
    CorrectionUncertaintyVerification,
    FreeFieldCorrection,
    UncertaintyComponentRow,
    adjustment_value,
    comparison_coupler_correction,
    correction_uncertainty_budget,
    electrostatic_actuator_correction,
    exact_frequencies,
    maximum_expanded_uncertainty,
    sound_calibrator_correction,
    verify_correction_uncertainty,
)
from .random_incidence import (
    IEC61183_TABLE_B1,
    DiffuseFieldSensitivity,
    DirectivityFactor,
    RandomIncidenceSensitivity,
    ReferenceMicrophoneRow,
    SphereDivisionWarning,
    adjustment_factors,
    axisymmetric_directivity_factor,
    diffuse_field_sensitivity,
    directivity_factor,
    equal_area_directivity_factor,
    equal_area_incidence_angles,
    largest_element_fraction,
    random_incidence_sensitivity,
)
from .reciprocity_calibration import (
    IEC61094_2_TABLE_1,
    IEC61094_3_TABLE_1,
    ReciprocityCalibration,
    ReciprocityUncertaintyBudget,
    ReciprocityUncertaintyRow,
    reciprocity_uncertainty_budget,
)
from .reciprocity_coupler import (
    IEC61094_2_TABLE_C1,
    IEC61094_2_TABLE_C2,
    IEC61094_2_TABLE_C3,
    CapillaryTube,
    CapillaryTubeImpedance,
    CouplerCheck,
    CouplerDimensions,
    CouplerInputUncertainties,
    CouplerParameterUncertainty,
    CouplerTransferImpedance,
    HeatConductionCorrection,
    LargeVolumeCoupler,
    PlaneWaveCoupler,
    ReciprocityMicrophone,
    WaveMotionCorrection,
    capillary_tube_impedance,
    check_coupler,
    coupler_parameter_uncertainty,
    coupler_transfer_impedance,
    heat_conduction_correction,
    large_volume_wave_motion_correction,
    microphone_acoustic_impedance,
    pressure_reciprocity,
    pressure_reciprocity_pair,
    temperature_transfer_function,
)
from .reciprocity_free_field import (
    AcousticCentre,
    FreeFieldArrangementCheck,
    FreeFieldInputUncertainties,
    FreeFieldParameterUncertainty,
    ReciprocityAirAttenuation,
    acoustic_centre,
    check_free_field_arrangement,
    free_field_parameter_uncertainty,
    free_field_reciprocity,
    free_field_reciprocity_pair,
    free_field_transfer_impedance,
    reciprocity_air_attenuation,
)
from .reference_values import ISO1683_REFERENCE_VALUES, ReferenceValue
from .sound_calibrator import (
    ABBREVIATED_FREQUENCY_ACCEPTANCE_LIMITS_PERCENT,
    ABBREVIATED_LEVEL_REDUCTIONS_DB,
    CALIBRATOR_CLASSES,
    CALIBRATOR_REQUIREMENTS,
    DISTORTION_ACCEPTANCE_LIMITS_PERCENT,
    DISTORTION_MAX_UNCERTAINTY_PERCENT,
    ENVIRONMENTAL_FREQUENCY_ACCEPTANCE_LIMITS_PERCENT,
    ENVIRONMENTAL_FREQUENCY_MAX_UNCERTAINTY_PERCENT,
    ENVIRONMENTAL_LEVEL_ACCEPTANCE_LIMITS_DB,
    ENVIRONMENTAL_LEVEL_MAX_UNCERTAINTY_DB,
    FIELD_IMMUNITY_ACCEPTANCE_LIMITS_DB,
    FIELD_IMMUNITY_MAX_UNCERTAINTY_DB,
    FLUCTUATION_ACCEPTANCE_LIMITS_DB,
    FLUCTUATION_MAX_UNCERTAINTY_DB,
    FREQUENCY_ACCEPTANCE_LIMITS_PERCENT,
    FREQUENCY_MAX_UNCERTAINTY_PERCENT,
    LEVEL_ACCEPTANCE_LIMITS_DB,
    LEVEL_MAX_UNCERTAINTY_DB,
    SUPPLY_VOLTAGE_ACCEPTANCE_LIMITS_DB,
    SUPPLY_VOLTAGE_MAX_UNCERTAINTY_DB,
    CalibratorTableRow,
    SoundCalibratorMeasurements,
    SoundCalibratorRequirement,
    SoundCalibratorVerification,
    verify_sound_calibrator,
)
from .sound_level_meter import (
    ACOUSTIC_TEST_FREQUENCIES_HZ,
    ELECTRICAL_TEST_FREQUENCIES_HZ,
    IEC61672_TABLE_4,
    IEC61672_TABLE_5,
    IEC61672_TABLE_B1,
    PERIODIC_TEST_ENVIRONMENT,
    SLM_PERIODIC_REQUIREMENTS,
    TONEBURST_TEST_DURATIONS_MS,
    MaxUncertaintyRow,
    PeakReference,
    SoundLevelMeterFeatures,
    SoundLevelMeterPeriodicMeasurements,
    SoundLevelMeterPeriodicRequirement,
    SoundLevelMeterPeriodicVerification,
    ToneburstReference,
    verify_sound_level_meter_periodic,
)
from .uncertainty import (
    MonteCarloResult,
    Quantity,
    UncertaintyResult,
    UncertaintyWarning,
    combine_uncertainty,
    coverage_factor,
    expanded_uncertainty,
    monte_carlo,
    rectangular,
    triangular,
    u_shaped,
)

__all__ = [
    "ABBREVIATED_FREQUENCY_ACCEPTANCE_LIMITS_PERCENT",
    "ABBREVIATED_LEVEL_REDUCTIONS_DB",
    "ACOUSTIC_TEST_FREQUENCIES_HZ",
    "CALIBRATOR_CLASSES",
    "CALIBRATOR_REQUIREMENTS",
    "DISTORTION_ACCEPTANCE_LIMITS_PERCENT",
    "DISTORTION_MAX_UNCERTAINTY_PERCENT",
    "ELECTRICAL_TEST_FREQUENCIES_HZ",
    "ENVIRONMENTAL_FREQUENCY_ACCEPTANCE_LIMITS_PERCENT",
    "ENVIRONMENTAL_FREQUENCY_MAX_UNCERTAINTY_PERCENT",
    "ENVIRONMENTAL_LEVEL_ACCEPTANCE_LIMITS_DB",
    "ENVIRONMENTAL_LEVEL_MAX_UNCERTAINTY_DB",
    "FIELD_IMMUNITY_ACCEPTANCE_LIMITS_DB",
    "FIELD_IMMUNITY_MAX_UNCERTAINTY_DB",
    "FLUCTUATION_ACCEPTANCE_LIMITS_DB",
    "FLUCTUATION_MAX_UNCERTAINTY_DB",
    "FREQUENCY_ACCEPTANCE_LIMITS_PERCENT",
    "FREQUENCY_MAX_UNCERTAINTY_PERCENT",
    "IEC61094_2_TABLE_1",
    "IEC61094_2_TABLE_C1",
    "IEC61094_2_TABLE_C2",
    "IEC61094_2_TABLE_C3",
    "IEC61094_3_TABLE_1",
    "IEC61094_5_TABLE_A1",
    "IEC61094_5_TABLE_D1",
    "IEC61094_8_TABLE_1",
    "IEC61094_8_TABLE_2",
    "IEC61183_TABLE_B1",
    "IEC61672_TABLE_4",
    "IEC61672_TABLE_5",
    "IEC61672_TABLE_B1",
    "IEC62585_TABLE_I1",
    "ISO1683_REFERENCE_VALUES",
    "LEVEL_ACCEPTANCE_LIMITS_DB",
    "LEVEL_MAX_UNCERTAINTY_DB",
    "PERIODIC_TEST_ENVIRONMENT",
    "SLM_PERIODIC_REQUIREMENTS",
    "SUPPLY_VOLTAGE_ACCEPTANCE_LIMITS_DB",
    "SUPPLY_VOLTAGE_MAX_UNCERTAINTY_DB",
    "TONEBURST_TEST_DURATIONS_MS",
    "AcousticCentre",
    "AdjustmentValue",
    "CalibrationWarning",
    "CalibratorTableRow",
    "CapillaryTube",
    "CapillaryTubeImpedance",
    "ComparisonCalibration",
    "ComparisonUncertaintyBudget",
    "ComparisonUncertaintyRow",
    "ConformanceVerification",
    "CorrectionUncertaintyBudget",
    "CorrectionUncertaintyVerification",
    "CouplerCheck",
    "CouplerDimensions",
    "CouplerInputUncertainties",
    "CouplerParameterUncertainty",
    "CouplerTransferImpedance",
    "DiffuseFieldSensitivity",
    "DirectivityFactor",
    "EnvironmentalSensitivityCorrection",
    "FreeFieldArrangementCheck",
    "FreeFieldCorrection",
    "FreeFieldInputUncertainties",
    "FreeFieldParameterUncertainty",
    "FreeFieldRegion",
    "HeatConductionCorrection",
    "JigDiameterCorrection",
    "LargeVolumeCoupler",
    "LevelCrossingResult",
    "MaxUncertaintyRow",
    "MonteCarloResult",
    "PeakReference",
    "PeakStatisticsResult",
    "PlaneWaveCoupler",
    "Quantity",
    "RandomIncidenceSensitivity",
    "ReciprocityAirAttenuation",
    "ReciprocityCalibration",
    "ReciprocityMicrophone",
    "ReciprocityUncertaintyBudget",
    "ReciprocityUncertaintyRow",
    "ReferenceCalibrationRow",
    "ReferenceMicrophoneRow",
    "ReferenceValue",
    "SoundCalibratorMeasurements",
    "SoundCalibratorRequirement",
    "SoundCalibratorVerification",
    "SoundLevelMeterFeatures",
    "SoundLevelMeterPeriodicMeasurements",
    "SoundLevelMeterPeriodicRequirement",
    "SoundLevelMeterPeriodicVerification",
    "SphereDivisionWarning",
    "StationarityTestResult",
    "ToneburstReference",
    "TrendTestResult",
    "UncertaintyComponentRow",
    "UncertaintyResult",
    "UncertaintyWarning",
    "WaveMotionCorrection",
    "acoustic_centre",
    "adjustment_factors",
    "adjustment_value",
    "axisymmetric_directivity_factor",
    "capillary_tube_impedance",
    "check_coupler",
    "check_free_field_arrangement",
    "combine_uncertainty",
    "comparison_coupler_correction",
    "comparison_uncertainty_budget",
    "correction_uncertainty_budget",
    "coupler_parameter_uncertainty",
    "coupler_transfer_impedance",
    "coverage_factor",
    "diffuse_field_sensitivity",
    "directivity_factor",
    "electrostatic_actuator_correction",
    "environmental_sensitivity_correction",
    "equal_area_directivity_factor",
    "equal_area_incidence_angles",
    "exact_frequencies",
    "expanded_uncertainty",
    "free_field_parameter_uncertainty",
    "free_field_reciprocity",
    "free_field_reciprocity_pair",
    "free_field_region",
    "free_field_transfer_impedance",
    "heat_conduction_correction",
    "jig_diameter_correction",
    "large_volume_wave_motion_correction",
    "largest_element_fraction",
    "level_crossing_rate",
    "maximum_expanded_uncertainty",
    "microphone_acoustic_impedance",
    "monte_carlo",
    "peak_statistics",
    "pressure_reciprocity",
    "pressure_reciprocity_pair",
    "random_incidence_sensitivity",
    "reciprocity_air_attenuation",
    "reciprocity_uncertainty_budget",
    "rectangular",
    "sensitivity",
    "sequential_comparison",
    "simultaneous_comparison",
    "sound_calibrator_correction",
    "stationarity_test",
    "temperature_transfer_function",
    "trend_test",
    "triangular",
    "u_shaped",
    "verify_conformance",
    "verify_correction_uncertainty",
    "verify_sound_calibrator",
    "verify_sound_level_meter_periodic",
]
