#  Copyright (c) 2026. Jose Manuel Requena Plens
"""vibration.immission subdomain of phonometry: measuring vibration immission.

The German immission-control chain: DIN 45669-1 defines the vibration meter
that DIN 4150-2 and DIN 4150-3 presuppose, and its Annex E turns the
frequency-dependent guideline curve of DIN 4150-3 into a comparison with one
number. DIN 45672-2 reduces the record of a passing train with that meter, and
Clause 4.5 of DIN 45672-1 reads the elastic constants of the ground from its
wave speeds.
"""

from __future__ import annotations

from .ground import (
    GROUND_WAVE_SPEED_RANGES_M_S,
    SHEAR_STRAIN_LINEAR_LIMIT,
    compression_wave_speed,
    poisson_ratio_from_wave_speeds,
    shear_modulus_from_wave_speed,
    shear_strain_amplitude,
    youngs_modulus_from_wave_speeds,
)
from .railway import (
    EVENT_REFERENCE_DURATION_S,
    NARROWBAND_RESOLUTION_HZ,
    PASSAGE_BANDS_HZ,
    T1_DURATION_S,
    THIRD_OCTAVE_LINES,
    VELOCITY_LEVEL_REFERENCE_MM_S,
    AmplitudeDistribution,
    TrainPassage,
    amplitude_distribution,
    band_sum_level,
    centred_interval,
    combined_event_velocity,
    elastic_insertion_loss,
    evaluate_train_passage,
    event_velocity,
    event_velocity_level,
    interval_rms,
    narrowband_psd,
    passage_average_level,
    passage_average_velocity,
    passage_energy_spectral_density,
    running_acceleration_level,
    running_velocity_level,
    running_velocity_rms,
    spectral_density_level,
    third_octaves_from_narrowband,
    velocity_psd_from_voltage,
)
from .vibration_meter import (
    ASSESSMENT_GUIDE_VALUES_MM_S,
    ASSESSMENT_WEIGHTING_TOLERANCE,
    BAND_LIMIT_CORNER_FACTOR,
    KB_CORNER_HZ,
    KB_DETECTION_LIMIT,
    KB_INDICATION_TOLERANCE_PERCENT,
    KB_PULSE_RESPONSE_PERCENT,
    KB_REFERENCE_FREQUENCY_HZ,
    KB_REFERENCE_INDICATIONS,
    KB_TEST_INDICATIONS,
    KB_TIME_CONSTANT_S,
    RESPONSE_TOLERANCE_LOWER_PERCENT,
    RESPONSE_TOLERANCE_UPPER_PERCENT,
    TAKT_DURATION_S,
    TAKT_SUPPRESSION_THRESHOLD,
    VELOCITY_DETECTION_LIMIT_MM_S,
    WORKING_RANGES_HZ,
    AssessmentVelocity,
    DominantFrequency,
    VibrationMeterReading,
    VibrationMeterVerification,
    assess_short_term_vibration,
    assessment_velocity,
    assessment_weighting_response,
    assessment_weighting_taps,
    band_limitation_response,
    dominant_frequency,
    kb_signal,
    kb_weighting_response,
    kbf_signal,
    measure_vibration_immission,
    response_tolerance_percent,
    takt_maxima,
    takt_maximum_rms,
    verify_vibration_meter,
)

__all__ = [
    "ASSESSMENT_GUIDE_VALUES_MM_S",
    "ASSESSMENT_WEIGHTING_TOLERANCE",
    "BAND_LIMIT_CORNER_FACTOR",
    "EVENT_REFERENCE_DURATION_S",
    "GROUND_WAVE_SPEED_RANGES_M_S",
    "KB_CORNER_HZ",
    "KB_DETECTION_LIMIT",
    "KB_INDICATION_TOLERANCE_PERCENT",
    "KB_PULSE_RESPONSE_PERCENT",
    "KB_REFERENCE_FREQUENCY_HZ",
    "KB_REFERENCE_INDICATIONS",
    "KB_TEST_INDICATIONS",
    "KB_TIME_CONSTANT_S",
    "NARROWBAND_RESOLUTION_HZ",
    "PASSAGE_BANDS_HZ",
    "RESPONSE_TOLERANCE_LOWER_PERCENT",
    "RESPONSE_TOLERANCE_UPPER_PERCENT",
    "SHEAR_STRAIN_LINEAR_LIMIT",
    "T1_DURATION_S",
    "TAKT_DURATION_S",
    "TAKT_SUPPRESSION_THRESHOLD",
    "THIRD_OCTAVE_LINES",
    "VELOCITY_DETECTION_LIMIT_MM_S",
    "VELOCITY_LEVEL_REFERENCE_MM_S",
    "WORKING_RANGES_HZ",
    "AmplitudeDistribution",
    "AssessmentVelocity",
    "DominantFrequency",
    "TrainPassage",
    "VibrationMeterReading",
    "VibrationMeterVerification",
    "amplitude_distribution",
    "assess_short_term_vibration",
    "assessment_velocity",
    "assessment_weighting_response",
    "assessment_weighting_taps",
    "band_limitation_response",
    "band_sum_level",
    "centred_interval",
    "combined_event_velocity",
    "compression_wave_speed",
    "dominant_frequency",
    "elastic_insertion_loss",
    "evaluate_train_passage",
    "event_velocity",
    "event_velocity_level",
    "interval_rms",
    "kb_signal",
    "kb_weighting_response",
    "kbf_signal",
    "measure_vibration_immission",
    "narrowband_psd",
    "passage_average_level",
    "passage_average_velocity",
    "passage_energy_spectral_density",
    "poisson_ratio_from_wave_speeds",
    "response_tolerance_percent",
    "running_acceleration_level",
    "running_velocity_level",
    "running_velocity_rms",
    "shear_modulus_from_wave_speed",
    "shear_strain_amplitude",
    "spectral_density_level",
    "takt_maxima",
    "takt_maximum_rms",
    "third_octaves_from_narrowband",
    "velocity_psd_from_voltage",
    "verify_vibration_meter",
    "youngs_modulus_from_wave_speeds",
]
