#  Copyright (c) 2026. Jose M. Requena-Plens
"""Generate the committed example ``.report()`` fiches.

Mirrors :mod:`scripts.generate_graphs` for the normative report PDFs: it builds
a small set of representative results with example metadata and writes their
``.report()`` fiche to ``.github/reports/`` so the repository always carries an
up-to-date rendered example of every report kind, which the documentation links
to. Alongside every ``<name>.pdf`` it rasterizes the first page to a
``<name>.png`` preview (via :mod:`pypdfium2`, no system Poppler needed) so the
website and the GitHub docs can show the fiche inline without a PDF viewer or a
build-time rasterizer. Run it with ``make reports`` or
``python scripts/generate_reports.py``.

Neither the PDFs nor the PNG previews are byte-checked in CI: the embedded plot
is vector geometry whose floating-point coordinates differ by ~1 ULP across
CPUs (and the raster inherits that), so a byte comparison would be as flaky as
the figure pipeline was before its tolerance check (which cannot apply to a
binary PDF). They are regenerated by the maintainer instead;
``tests/test_generate_reports.py`` only asserts the generator still produces a
valid one-page PDF and a valid PNG preview for each example.
"""

from __future__ import annotations

import argparse
import os
from typing import Callable, List, Tuple

import numpy as np

import phonometry as ph
from phonometry import ReportMetadata

#: Committed output directory for the example fiches.
_DEFAULT_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", ".github", "reports")
)

#: Pixel width of the rendered PNG preview. A4 portrait at this width is ~1415
#: px tall: crisp on the docs pages (shown at ~80 % column width) yet small
#: enough to commit. The height follows from the page aspect ratio.
_PREVIEW_WIDTH_PX = 1000

_RATING_FREQS = np.array(
    [100, 125, 160, 200, 250, 315, 400, 500, 630, 800,
     1000, 1250, 1600, 2000, 2500, 3150],
    dtype=float,
)


def _airborne_example() -> Tuple[object, ReportMetadata, str]:
    """Airborne fiche: a predicted single-panel sound reduction index."""
    result = ph.single_panel_transmission_loss(
        _RATING_FREQS, 15.0, critical_frequency=2000.0, loss_factor=0.02
    )
    metadata = ReportMetadata(
        specimen="6 mm float glass pane",
        client="Example client",
        manufacturer="Example glassworks",
        area=1.23,
        mass_per_area=15.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=21.6,
        source_relative_humidity=35.3,
        receiving_temperature=20.9,
        receiving_relative_humidity=37.4,
        pressure=101.9,
        test_room="Transmission suite (example)",
        mounting="Elastic perimeter, single glazing",
        measurement_standard="ISO 10140-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-1",
        requirement=30.0,
    )
    return result, metadata, "iso717_airborne_example.pdf"


def _impact_example() -> Tuple[object, ReportMetadata, str]:
    """Impact fiche: a normalized impact sound pressure level rating."""
    ln = np.array(
        [45, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 55, 52, 49, 46],
        dtype=float,
    )
    result = ph.weighted_impact_rating(ln)
    metadata = ReportMetadata(
        specimen="150 mm concrete slab with a floating floor",
        client="Example client",
        manufacturer="Example floors",
        area=16.0,
        mass_per_area=360.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=20.8,
        source_relative_humidity=47.0,
        receiving_temperature=20.5,
        receiving_relative_humidity=48.0,
        pressure=100.9,
        test_room="Transmission suite (example)",
        mounting="Floating floor on a resilient layer",
        measurement_standard="ISO 16283-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-2",
        requirement=53.0,
    )
    return result, metadata, "iso717_impact_example.pdf"


#: Every example fiche the repository keeps rendered. New report kinds append
#: their factory here so ``make reports`` regenerates the full set.
_EXAMPLES: List[Callable[[], Tuple[object, ReportMetadata, str]]] = [
    _airborne_example,
    _impact_example,
]


def preview_path_for(pdf_path: str) -> str:
    """Return the PNG-preview path that pairs with ``pdf_path`` (``.pdf`` -> ``.png``)."""
    return os.path.splitext(pdf_path)[0] + ".png"


def _optimize_png(path: str) -> None:
    """Losslessly recompress ``path`` in place with ``oxipng`` when available.

    Mirrors :func:`scripts.generate_graphs._optimize_png`: the transform never
    changes a pixel, so it only shrinks the committed file; a missing optimizer
    degrades to a larger-but-identical PNG rather than an error.
    """
    try:
        import oxipng
    except ImportError:
        print(f"[reports] pyoxipng not installed; {os.path.basename(path)} "
              "saved unoptimized")
        return
    # Match scripts/generate_graphs._optimize_png: level 6 is an exhaustive
    # filter/deflate search whose result is fixed by the input (not the
    # thread count), so the output is deterministic without paying for zopfli.
    oxipng.optimize(path, level=6, strip=oxipng.StripChunks.safe())


def _write_preview(pdf_path: str) -> str:
    """Rasterize the first page of ``pdf_path`` to a PNG preview beside it.

    The preview is what the documentation embeds inline; it is not byte-checked
    (the raster inherits the vector plot's ~1 ULP cross-CPU drift), so it is
    regenerated by the maintainer like the figures.
    """
    import pypdfium2 as pdfium

    pdf = pdfium.PdfDocument(pdf_path)
    try:
        page = pdf[0]
        width_pt, _ = page.get_size()
        scale = _PREVIEW_WIDTH_PX / width_pt
        image = page.render(scale=scale).to_pil()
        png_path = preview_path_for(pdf_path)
        # RGB (no alpha): the fiche is opaque white; a smaller, simpler PNG.
        image.convert("RGB").save(png_path, format="PNG", optimize=True)
    finally:
        pdf.close()
    _optimize_png(png_path)
    return png_path


def generate_reports(output_dir: str) -> List[str]:
    """Write every example fiche (PDF + PNG preview) into ``output_dir``.

    Returns the PDF paths written; each has a paired ``.png`` preview next to it
    (see :func:`preview_path_for`).
    """
    os.makedirs(output_dir, exist_ok=True)
    written: List[str] = []
    for factory in _EXAMPLES:
        result, metadata, name = factory()
        path = os.path.join(output_dir, name)
        result.report(path, metadata=metadata)  # type: ignore[attr-defined]
        _write_preview(path)
        written.append(path)
    return written


def main() -> None:
    """Generate the example fiches into the committed directory (or ``--output-dir``)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default=_DEFAULT_DIR)
    args = parser.parse_args()
    for path in generate_reports(os.path.abspath(args.output_dir)):
        print(f"wrote {path}")
        print(f"wrote {preview_path_for(path)}")


if __name__ == "__main__":
    main()
