#  Copyright (c) 2026. Jose M. Requena-Plens
"""Generate the committed example ``.report()`` fiches.

Mirrors :mod:`scripts.generate_graphs` for the normative report PDFs: it builds
a small set of representative results with example metadata and writes their
``.report()`` fiche to ``.github/reports/`` so the repository always carries an
up-to-date rendered example of every report kind, which the documentation links
to. Alongside every ``<name>.pdf`` it rasterizes the first page to a
``<name>.png`` preview (via :mod:`pypdfium2`, no system Poppler needed) so the
website and the GitHub docs can show the fiche inline without a PDF viewer or a
build-time rasterizer. Run it with ``make reports`` or
``python scripts/generate_reports.py``.

Neither the PDFs nor the PNG previews are byte-checked in CI: the embedded plot
is vector geometry whose floating-point coordinates differ by ~1 ULP across
CPUs (and the raster inherits that), so a byte comparison would be as flaky as
the figure pipeline was before its tolerance check (which cannot apply to a
binary PDF). They are regenerated by the maintainer instead;
``tests/test_generate_reports.py`` only asserts the generator still produces a
valid one-page PDF and a valid PNG preview for each example.
"""

from __future__ import annotations

import argparse
import os
from typing import Callable, List, Tuple

import numpy as np

import phonometry as ph
from phonometry import ReportMetadata

#: Committed output directory for the example fiches.
_DEFAULT_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", ".github", "reports")
)

#: Pixel width of the rendered PNG preview. A4 portrait at this width is ~1415
#: px tall: crisp on the docs pages (shown at ~80 % column width) yet small
#: enough to commit. The height follows from the page aspect ratio.
_PREVIEW_WIDTH_PX = 1000

_RATING_FREQS = np.array(
    [100, 125, 160, 200, 250, 315, 400, 500, 630, 800,
     1000, 1250, 1600, 2000, 2500, 3150],
    dtype=float,
)


def _airborne_example() -> Tuple[object, ReportMetadata, str]:
    """Airborne fiche: a predicted single-panel sound reduction index."""
    result = ph.single_panel_transmission_loss(
        _RATING_FREQS, 15.0, critical_frequency=2000.0, loss_factor=0.02
    )
    metadata = ReportMetadata(
        specimen="6 mm float glass pane",
        client="Example client",
        manufacturer="Example glassworks",
        area=1.23,
        mass_per_area=15.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=21.6,
        source_relative_humidity=35.3,
        receiving_temperature=20.9,
        receiving_relative_humidity=37.4,
        pressure=101.9,
        test_room="Transmission suite (example)",
        mounting="Elastic perimeter, single glazing",
        measurement_standard="ISO 10140-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-1",
        requirement=30.0,
    )
    return result, metadata, "iso717_airborne_example.pdf"


def _impact_example() -> Tuple[object, ReportMetadata, str]:
    """Impact fiche: a normalized impact sound pressure level rating."""
    ln = np.array(
        [45, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 55, 52, 49, 46],
        dtype=float,
    )
    result = ph.weighted_impact_rating(ln)
    metadata = ReportMetadata(
        specimen="150 mm concrete slab with a floating floor",
        client="Example client",
        manufacturer="Example floors",
        area=16.0,
        mass_per_area=360.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=20.8,
        source_relative_humidity=47.0,
        receiving_temperature=20.5,
        receiving_relative_humidity=48.0,
        pressure=100.9,
        test_room="Transmission suite (example)",
        mounting="Floating floor on a resilient layer",
        measurement_standard="ISO 16283-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-2",
        requirement=53.0,
    )
    return result, metadata, "iso717_impact_example.pdf"


def _field_airborne_example() -> Tuple[object, ReportMetadata, str]:
    """Field airborne fiche: a DnT measurement between dwellings (ISO 16283-1)."""
    l1 = np.array(
        [92.3, 93.1, 94.0, 94.4, 94.8, 95.0, 95.2, 95.4,
         95.3, 95.1, 94.8, 94.4, 93.9, 93.3, 92.5, 91.6]
    )
    d = np.array(
        [38.2, 40.1, 42.6, 45.2, 47.8, 50.1, 52.3, 54.0,
         55.6, 57.1, 58.2, 59.0, 59.6, 60.1, 60.3, 59.8]
    )
    t2 = np.array(
        [0.62, 0.58, 0.55, 0.53, 0.52, 0.50, 0.49, 0.48,
         0.47, 0.46, 0.45, 0.45, 0.44, 0.43, 0.43, 0.42]
    )
    result = ph.airborne_insulation(l1, l1 - d, t2, area=12.5, volume=30.4)
    metadata = ReportMetadata(
        specimen="Separating wall, 240 mm brick with independent lining",
        client="Example client",
        area=12.5,
        source_volume=32.1,
        receiving_volume=30.4,
        temperature=20.4,
        relative_humidity=52.0,
        test_room="Dwelling A living room to dwelling B living room",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-16283-1",
        requirement=50.0,
    )
    return result, metadata, "iso16283_airborne_example.pdf"


def _field_impact_example() -> Tuple[object, ReportMetadata, str]:
    """Field impact fiche: a tapping-machine L'nT measurement (ISO 16283-2)."""
    li = np.array(
        [58.0, 60.5, 62.0, 63.5, 65.0, 66.0, 66.5, 66.0,
         65.5, 65.0, 64.0, 62.0, 59.0, 56.0, 53.0, 50.0]
    )
    t2 = np.array(
        [0.60, 0.57, 0.55, 0.53, 0.52, 0.50, 0.49, 0.48,
         0.47, 0.46, 0.45, 0.45, 0.44, 0.43, 0.43, 0.42]
    )
    result = ph.impact_insulation(li, t2, volume=30.4)
    metadata = ReportMetadata(
        specimen="Timber-joist floor with a floating chipboard deck",
        client="Example client",
        receiving_volume=30.4,
        temperature=20.1,
        relative_humidity=54.0,
        test_room="Dwelling A bedroom below dwelling B bedroom",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-16283-2",
        requirement=58.0,
    )
    return result, metadata, "iso16283_impact_example.pdf"


def _absorption_example() -> Tuple[object, ReportMetadata, str]:
    """Absorption fiche: an ISO 11654 weighted sound absorption rating."""
    # The fifteen one-third-octave alpha_s (200 Hz to 5000 Hz) an accredited
    # ISO 354 certificate reports, whose octave means are the practical
    # coefficients (0.35, 1.00, 0.65, 0.60, 0.55) giving alpha_w = 0.60 with an
    # M shape indicator (ISO 11654 Annex A.2 shape); a broadband porous absorber.
    alpha_s = (
        0.30, 0.35, 0.40,   # 250 Hz octave -> alpha_p 0.35
        1.00, 1.00, 1.00,   # 500 Hz octave -> alpha_p 1.00
        0.62, 0.66, 0.67,   # 1000 Hz octave -> alpha_p 0.65
        0.58, 0.60, 0.62,   # 2000 Hz octave -> alpha_p 0.60
        0.53, 0.55, 0.57,   # 4000 Hz octave -> alpha_p 0.55
    )
    result = ph.materials.weighted_absorption_from_third_octave(alpha_s)
    metadata = ReportMetadata(
        specimen="50 mm porous absorber over a 100 mm air gap",
        client="Example client",
        manufacturer="Example acoustics",
        area=10.8,
        mounting="Type A (mounted directly against a rigid wall)",
        test_room="Reverberation room (example)",
        measurement_standard="ISO 354",
        test_date="2026-07-20",
        temperature=21.4,
        relative_humidity=54.0,
        pressure=101.0,
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-11654",
        requirement=0.55,
    )
    return result, metadata, "iso11654_absorption_example.pdf"


def _loudness_example() -> Tuple[object, ReportMetadata, str]:
    """Loudness fiche: an ISO 532-1 Zwicker stationary loudness rating."""
    # A shaped 28-band one-third-octave spectrum (25 Hz..12.5 kHz) of a steady
    # appliance noise, descending with frequency.
    levels = np.array(
        [55, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
         42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29],
        dtype=float,
    )
    result = ph.loudness_zwicker_from_spectrum(levels, field="free")
    metadata = ReportMetadata(
        specimen="Household appliance, steady operating noise",
        client="Example client",
        manufacturer="Example appliances",
        test_room="Hemi-anechoic room (example)",
        measurement_standard="ISO 532-1 method 1",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-532",
        requirement=12.0,
    )
    return result, metadata, "iso532_loudness_example.pdf"


def _program_loudness_example() -> Tuple[object, ReportMetadata, str]:
    """Programme-loudness fiche: an EBU R 128 compliance measurement.

    The signal is the EBU Tech 3342 Case 1 loudness-range shape (two 20 s
    stereo 1 kHz tone segments 10 dB apart) trimmed 0.4 dB to -20.4 and
    -30.4 dBFS, giving a loudness range near 10 LU with the integrated
    loudness on the -23.0 LUFS target, inside the default +-0.2 LU QC
    tolerance of EBU R 128 item i).
    """
    fs = 48000
    t = np.arange(int(round(20.0 * fs))) / fs
    tone = np.sin(2.0 * np.pi * 1000.0 * t)
    seg_hi = 10.0 ** (-20.4 / 20.0) * tone
    seg_lo = 10.0 ** (-30.4 / 20.0) * tone
    mono = np.concatenate([seg_hi, seg_lo])
    signal = np.vstack([mono, mono])
    result = ph.broadcast.program_loudness(signal, fs)
    metadata = ReportMetadata(
        specimen="Reference tone sequence (-20.4 / -30.4 dBFS steps)",
        client="Example broadcaster",
        manufacturer="Example post-production",
        test_room="Reference monitoring room (example)",
        measurement_standard="EBU R 128",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-R128",
        requirement=-23.0,
    )
    return result, metadata, "ebu_r128_loudness_example.pdf"


def _epnl_example() -> Tuple[object, ReportMetadata, str]:
    """EPNL fiche: an ICAO Annex 16 aircraft-noise-certification result.

    A deterministic synthetic half-second flyover: a broadband spectral shape
    peaking near 400 Hz swept by a Gaussian temporal gain (the aircraft
    approaching and receding) with a 2500 Hz fan tone that adds the tone
    correction, giving a valid ``EPNLResult`` with a peak PNLTM near mid-record
    and a clear 10 dB-down window. The requirement is a plausible certification
    EPNL limit the example passes.
    """
    k, dt = 24, 0.5
    idx = np.arange(k)
    shape = 15.0 * np.exp(-((np.log10(ph.aircraft.NOY_BANDS) - np.log10(400.0)) ** 2) / 0.5)
    gain = 24.0 * np.exp(-((idx - 12.0) ** 2) / (2 * 3.5**2)) - 3.0
    spectra = (46.0 + shape)[None, :] + gain[:, None]
    spectra[:, 17] += 10.0 * np.exp(-((idx - 12.0) ** 2) / (2 * 4.0**2))  # 2500 Hz tone
    result = ph.effective_perceived_noise_level(spectra, dt)
    metadata = ReportMetadata(
        specimen="Example twin-turbofan transport (synthetic flyover)",
        manufacturer="Example Aircraft Company",
        client="Example Aircraft Company",
        test_room="Flyover reference point",
        measurement_standard="ICAO Annex 16 Vol I Amendment 14 Chapter 4",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-EPNL",
        requirement=101.0,
    )
    return result, metadata, "icao_epnl_example.pdf"


def _filter_class_example() -> Tuple[object, ReportMetadata, str]:
    """Filter-compliance fiche: an IEC 61260-1 octave-band class verification.

    The library default (Butterworth order 6) octave bank from 125 Hz to
    4 kHz clears class 1 across every band, so the fiche boxes a Class 1
    COMPLIES result and passes the required-class-1 verdict.
    """
    bank = ph.OctaveFilterBank(fs=48000, fraction=1, order=6, limits=[125, 4000])
    result = ph.filter_class_compliance(bank)
    metadata = ReportMetadata(
        specimen="1/1-octave filter bank",
        client="Example client",
        manufacturer="Example instruments",
        test_room="Electroacoustics laboratory (example)",
        measurement_standard="IEC 61260-1:2014",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-61260",
        required_class=1,
    )
    return result, metadata, "iec61260_filter_example.pdf"


def _filter_class_1995_example() -> Tuple[object, ReportMetadata, str]:
    """Filter-compliance fiche under the 1995 edition, which keeps class 0.

    IEC 61260-1:2014 dropped class 0; the older IEC 61260:1995 /
    ANSI S1.11-2004 retains it. Selecting ``edition="1995"`` verifies against
    that mask, and the default (order 6) octave bank clears the stricter
    class 0, so the fiche boxes a Class 0 COMPLIES result.
    """
    bank = ph.OctaveFilterBank(fs=48000, fraction=1, order=6, limits=[250, 4000])
    result = ph.filter_class_compliance(bank, edition="1995")
    metadata = ReportMetadata(
        specimen="1/1-octave filter bank",
        client="Example client",
        manufacturer="Example instruments",
        test_room="Electroacoustics laboratory (example)",
        measurement_standard="IEC 61260:1995",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-61260-1995",
        required_class=0,
    )
    return result, metadata, "iec61260_filter_1995_example.pdf"


def _iso4871_declaration_example() -> Tuple[object, ReportMetadata, str]:
    """ISO 4871 fiche: a dual-number machinery noise-emission declaration.

    Reproduces the ISO 4871:1996 Annex B.2 example (Type 990, Model 11-TC): two
    operating modes with a measured A-weighted sound power level and an
    uncertainty of 2 dB, giving declared values L_WAd = 90 and 97 dB (Annex B.1),
    plus emission sound pressure levels at the work station. A verification
    measurement is added per mode: mode 1 passes (89 <= 90) and mode 2 fails
    (98 > 97), exercising the clause 6.2 verdict both ways.
    """
    mode1 = ph.OperatingModeDeclaration(
        mode="Operating mode 1",
        sound_power_level=88.0,
        sound_power_uncertainty=2.0,
        emission_pressure_level=78.0,
        emission_pressure_uncertainty=2.0,
        verification_level=89.0,
    )
    mode2 = ph.OperatingModeDeclaration(
        mode="Operating mode 2",
        sound_power_level=95.0,
        sound_power_uncertainty=2.0,
        emission_pressure_level=86.0,
        emission_pressure_uncertainty=2.0,
        verification_level=98.0,
    )
    result = ph.NoiseEmissionDeclaration(
        modes=(mode1, mode2),
        machine="Type 990, Model 11-TC",
        operating_conditions="50 Hz, 230 V, rated load",
        noise_test_code="ISO 3746 test code (example)",
        basic_standards=("ISO 3744", "ISO 11202"),
        form="dual-number",
    )
    metadata = ReportMetadata(
        measurement_standard="ISO 3744",
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-4871",
        notes="Declaration reproduces the ISO 4871:1996 Annex B example machine.",
    )
    return result, metadata, "iso4871_declaration_example.pdf"


def _loudspeaker_example() -> Tuple[object, ReportMetadata, str]:
    """IEC 60268-5 fiche: the rated characteristics of a two-way loudspeaker.

    A synthetic on-axis response of an 8 ohm bookshelf loudspeaker: a flat
    passband near 87 dB with a gentle ripple, a low-frequency roll-off below
    50 Hz and a high-frequency roll-off above 16 kHz, so the effective frequency
    range (IEC 60268-5 21.2) sits inside the measured band. The characteristic
    sensitivity is referred to 1 W into 8 ohm at 1 m (the default 2,83 V drive),
    and the impedance modulus, the total-harmonic-distortion curve and a baffled
    circular-piston directivity feed the impedance, THD and polar panels. The
    requirement is a characteristic sensitivity the example clears.
    """
    freqs = np.geomspace(30.0, 24000.0, 320)
    reference = 87.0
    spl = reference + 1.2 * np.sin(2.0 * np.log2(freqs / 900.0))
    spl -= 10.0 * np.log10(1.0 + (50.0 / freqs) ** 6)      # LF roll-off
    spl -= 10.0 * np.log10(1.0 + (freqs / 16000.0) ** 7)   # HF roll-off

    imp_freqs = np.geomspace(20.0, 20000.0, 260)
    impedance = (
        6.6
        + 24.0 * np.exp(-((np.log2(imp_freqs / 52.0)) ** 2) / 0.12)   # resonance peak
        + 5.0 * (imp_freqs / 20000.0) ** 1.5                          # voice-coil rise
    )

    thd_freqs = np.geomspace(50.0, 5000.0, 140)
    thd_percent = 0.3 + 2.6 * np.exp(-((np.log2(thd_freqs / 70.0)) ** 2) / 0.45)

    angles = np.radians(np.linspace(0.0, 90.0, 46))
    directivity = ph.radiating_piston(
        0.075, np.array([1000.0, 2000.0, 4000.0]), angles=angles
    )

    result = ph.loudspeaker_characteristics(
        freqs, spl, 8.0,
        sensitivity_band=(200.0, 4000.0),
        tolerance_db=3.0,
        rated_frequency_range=(45.0, 22000.0),
        rated_noise_power=80.0,
        rated_sinusoidal_power=120.0,
        resonance_frequency=52.0,
        impedance=(imp_freqs, impedance),
        distortion=(thd_freqs, thd_percent),
        directivity=directivity,
        polar_frequency=2000.0,
    )
    metadata = ReportMetadata(
        specimen="Two-way bookshelf loudspeaker, 165 mm woofer",
        client="Example client",
        manufacturer="Example audio",
        test_room="Anechoic chamber (example)",
        mounting="Free field, on the tweeter axis at 1 m",
        measurement_standard="IEC 60268-5",
        temperature=21.0,
        relative_humidity=45.0,
        pressure=101.3,
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-60268-5",
        requirement=84.0,
    )
    return result, metadata, "iec60268_5_loudspeaker_example.pdf"


def _microphone_example() -> Tuple[object, ReportMetadata, str]:
    """IEC 60268-4 fiche: the rated characteristics of a cardioid condenser mic.

    A synthetic free-field response of a phantom-powered studio condenser
    microphone: flat around the 1 kHz reference with a gentle +2 dB presence
    region near 9 kHz, a low-frequency roll-off crossing -3 dB near 30 Hz and a
    high-frequency roll-off crossing -3 dB near 19 kHz, so the effective
    frequency range (IEC 60268-4 12.2) sits inside the measured band. The rated
    free-field sensitivity of 12,5 mV/Pa gives a sensitivity level of
    20 lg 0,0125 = -38,1 dB re 1 V/Pa (11.1); the A-weighted inherent-noise
    voltage yields the equivalent noise level (17.2); the ideal-cardioid
    directional pattern at 1 kHz yields a directivity index of 10 lg 3 = 4,8 dB
    (13.2.2); and the distortion-against-level curve places the overload sound
    pressure level at the 0,5 % THD limit (15.2). The requirement is a maximum
    equivalent noise level the example clears.
    """
    freqs = np.geomspace(20.0, 20000.0, 400)
    response = (
        -10.0 * np.log10(1.0 + (30.0 / freqs) ** 4)      # LF roll-off
        - 10.0 * np.log10(1.0 + (freqs / 19000.0) ** 8)  # HF roll-off
        + 2.0 * np.exp(-((np.log2(freqs / 9000.0)) ** 2) / 0.3)  # presence
    )

    angles = np.linspace(0.0, 179.0, 359)
    cardioid_db = 20.0 * np.log10((1.0 + np.cos(np.radians(angles))) / 2.0)

    thd_spl = np.linspace(100.0, 140.0, 81)
    thd_percent = 0.5 * 10.0 ** ((thd_spl - 130.0) * 0.08)

    noise_freqs = np.geomspace(20.0, 20000.0, 31)
    noise_levels = 18.0 - 5.4 * np.log2(noise_freqs / 20.0) + 1.5 * np.sin(
        np.log2(noise_freqs)
    )

    result = ph.microphone_characteristics(
        freqs, response, 12.5,
        tolerance_db=3.0,
        rated_impedance=150.0,
        minimum_load_impedance=1000.0,
        noise_voltage=1.25e-6,
        max_spl_thd_percent=0.5,
        distortion=(thd_spl, thd_percent),
        noise_spectrum=(noise_freqs, noise_levels),
        polar=(angles, cardioid_db),
        polar_frequency=1000.0,
        powering="Phantom P48 (IEC 61938)",
        supply_current_ma=3.1,
    )
    metadata = ReportMetadata(
        specimen="Cardioid condenser microphone, 25 mm capsule",
        client="Example client",
        manufacturer="Example audio",
        test_room="Anechoic chamber (example)",
        mounting="Free field, reference axis towards the source at 1 m",
        measurement_standard="IEC 60268-4",
        temperature=21.0,
        relative_humidity=45.0,
        pressure=101.3,
        test_date="2026-07-20",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-60268-4",
        requirement=16.0,
    )
    return result, metadata, "iec60268_4_microphone_example.pdf"


#: Every example fiche the repository keeps rendered. New report kinds append
#: their factory here so ``make reports`` regenerates the full set.
_EXAMPLES: List[Callable[[], Tuple[object, ReportMetadata, str]]] = [
    _airborne_example,
    _impact_example,
    _field_airborne_example,
    _field_impact_example,
    _absorption_example,
    _loudness_example,
    _program_loudness_example,
    _epnl_example,
    _filter_class_example,
    _filter_class_1995_example,
    _iso4871_declaration_example,
    _loudspeaker_example,
    _microphone_example,
]


def preview_path_for(pdf_path: str) -> str:
    """Return the PNG-preview path that pairs with ``pdf_path`` (``.pdf`` -> ``.png``)."""
    return os.path.splitext(pdf_path)[0] + ".png"


def _optimize_png(path: str) -> None:
    """Losslessly recompress ``path`` in place with ``oxipng`` when available.

    Mirrors :func:`scripts.generate_graphs._optimize_png`: the transform never
    changes a pixel, so it only shrinks the committed file; a missing optimizer
    degrades to a larger-but-identical PNG rather than an error.
    """
    try:
        import oxipng
    except ImportError:
        print(f"[reports] pyoxipng not installed; {os.path.basename(path)} "
              "saved unoptimized")
        return
    # Match scripts/generate_graphs._optimize_png: level 6 is an exhaustive
    # filter/deflate search whose result is fixed by the input (not the
    # thread count), so the output is deterministic without paying for zopfli.
    oxipng.optimize(path, level=6, strip=oxipng.StripChunks.safe())


def _write_preview(pdf_path: str) -> str:
    """Rasterize the first page of ``pdf_path`` to a PNG preview beside it.

    The preview is what the documentation embeds inline; it is not byte-checked
    (the raster inherits the vector plot's ~1 ULP cross-CPU drift), so it is
    regenerated by the maintainer like the figures.
    """
    import pypdfium2 as pdfium

    pdf = pdfium.PdfDocument(pdf_path)
    try:
        page = pdf[0]
        width_pt, _ = page.get_size()
        scale = _PREVIEW_WIDTH_PX / width_pt
        image = page.render(scale=scale).to_pil()
        png_path = preview_path_for(pdf_path)
        # RGB (no alpha): the fiche is opaque white; a smaller, simpler PNG.
        image.convert("RGB").save(png_path, format="PNG", optimize=True)
    finally:
        pdf.close()
    _optimize_png(png_path)
    return png_path


def generate_reports(output_dir: str) -> List[str]:
    """Write every example fiche (PDF + PNG preview) into ``output_dir``.

    Returns the PDF paths written; each has a paired ``.png`` preview next to it
    (see :func:`preview_path_for`).
    """
    os.makedirs(output_dir, exist_ok=True)
    written: List[str] = []
    for factory in _EXAMPLES:
        result, metadata, name = factory()
        path = os.path.join(output_dir, name)
        result.report(path, metadata=metadata)  # type: ignore[attr-defined]
        _write_preview(path)
        written.append(path)
    return written


def main() -> None:
    """Generate the example fiches into the committed directory (or ``--output-dir``)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default=_DEFAULT_DIR)
    args = parser.parse_args()
    for path in generate_reports(os.path.abspath(args.output_dir)):
        print(f"wrote {path}")
        print(f"wrote {preview_path_for(path)}")


if __name__ == "__main__":
    main()
