#  Copyright (c) 2026. Jose M. Requena-Plens
"""Generate the committed example ``.report()`` fiches.

Mirrors :mod:`scripts.generate_graphs` for the normative report PDFs: it builds
a small set of representative results with example metadata and writes their
``.report()`` fiche to ``.github/reports/`` so the repository always carries an
up-to-date rendered example of every report kind, which the documentation links
to. Run it with ``make reports`` or ``python scripts/generate_reports.py``.

The PDFs are NOT byte-checked in CI: the embedded plot is vector geometry whose
floating-point coordinates differ by ~1 ULP across CPUs, so a byte comparison
would be as flaky as the figure pipeline was before its tolerance check (which
cannot apply to a binary PDF). They are regenerated by the maintainer instead;
``tests/test_generate_reports.py`` only asserts the generator still produces a
valid one-page PDF for each example.
"""

from __future__ import annotations

import argparse
import os
from typing import Callable, List, Tuple

import numpy as np

import phonometry as ph
from phonometry import ReportMetadata

#: Committed output directory for the example fiches.
_DEFAULT_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", ".github", "reports")
)

_RATING_FREQS = np.array(
    [100, 125, 160, 200, 250, 315, 400, 500, 630, 800,
     1000, 1250, 1600, 2000, 2500, 3150],
    dtype=float,
)


def _airborne_example() -> Tuple[object, ReportMetadata, str]:
    """Airborne fiche: a predicted single-panel sound reduction index."""
    result = ph.single_panel_transmission_loss(
        _RATING_FREQS, 15.0, critical_frequency=2000.0, loss_factor=0.02
    )
    metadata = ReportMetadata(
        specimen="6 mm float glass pane",
        client="Example client",
        manufacturer="Example glassworks",
        area=1.23,
        mass_per_area=15.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=21.6,
        source_relative_humidity=35.3,
        receiving_temperature=20.9,
        receiving_relative_humidity=37.4,
        pressure=101.9,
        test_room="Transmission suite (example)",
        mounting="Elastic perimeter, single glazing",
        measurement_standard="ISO 10140-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-1",
        requirement=30.0,
    )
    return result, metadata, "iso717_airborne_example.pdf"


def _impact_example() -> Tuple[object, ReportMetadata, str]:
    """Impact fiche: a normalized impact sound pressure level rating."""
    ln = np.array(
        [45, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 55, 52, 49, 46],
        dtype=float,
    )
    result = ph.weighted_impact_rating(ln)
    metadata = ReportMetadata(
        specimen="150 mm concrete slab with a floating floor",
        client="Example client",
        manufacturer="Example floors",
        area=16.0,
        mass_per_area=360.0,
        source_volume=53.0,
        receiving_volume=51.0,
        source_temperature=20.8,
        source_relative_humidity=47.0,
        receiving_temperature=20.5,
        receiving_relative_humidity=48.0,
        pressure=100.9,
        test_room="Transmission suite (example)",
        mounting="Floating floor on a resilient layer",
        measurement_standard="ISO 16283-2",
        test_date="2026-07-18",
        laboratory="Phonometry reference example",
        operator="phonometry",
        report_id="EXAMPLE-717-2",
        requirement=53.0,
    )
    return result, metadata, "iso717_impact_example.pdf"


#: Every example fiche the repository keeps rendered. New report kinds append
#: their factory here so ``make reports`` regenerates the full set.
_EXAMPLES: List[Callable[[], Tuple[object, ReportMetadata, str]]] = [
    _airborne_example,
    _impact_example,
]


def generate_reports(output_dir: str) -> List[str]:
    """Write every example fiche into ``output_dir``; return the paths written."""
    os.makedirs(output_dir, exist_ok=True)
    written: List[str] = []
    for factory in _EXAMPLES:
        result, metadata, name = factory()
        path = os.path.join(output_dir, name)
        result.report(path, metadata=metadata)  # type: ignore[attr-defined]
        written.append(path)
    return written


def main() -> None:
    """Generate the example fiches into the committed directory (or ``--output-dir``)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default=_DEFAULT_DIR)
    args = parser.parse_args()
    for path in generate_reports(os.path.abspath(args.output_dir)):
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
